[tasks.serve]
run = """
  watchexec --restart --clear --wrap-process=session --stop-signal \
  SIGTERM --exts rs --watch src/ -- "cargo run"
"""
description = "run the CLI"

[tasks.format]
run = "cargo fix --allow-dirty"
