@baseUrl = http://localhost:5000
###
GET {{baseUrl}}/api/books
###
POST {{baseUrl}}/api/books
Content-Type: application/json

{
  "name": "hoge"
}
###
PUT {{baseUrl}}/api/books
Content-Type: application/json

{
  "name": "hoge"
}